'use client';

import React, { useState, useMemo, useRef } from 'react';
import { useJobTracker } from '../hooks/useJobTracker';
import StatsHeader from '../components/StatsHeader';
import KanbanBoard from '../components/KanbanBoard';
import ListView from '../components/ListView';
import AnalyticsView from '../components/AnalyticsView';
import JobModal from '../components/JobModal';
import { ViewMode, Job, JobStatus, LocationType } from '../types';
import { Plus, Search, LayoutGrid, List, BarChart3, Download, Upload, RotateCcw, Briefcase } from 'lucide-react';

export default function Home() {
  const {
    jobs,
    isLoaded,
    addJob,
    updateJob,
    deleteJob,
    moveJob,
    importData,
    resetData,
    stats,
  } = useJobTracker();

  // Search & Filter state
  const [search, setSearch] = useState('');
  const [statusFilter, setStatusFilter] = useState<JobStatus | 'all'>('all');
  const [locationTypeFilter, setLocationTypeFilter] = useState<LocationType | 'all'>('all');
  const [sortBy, setSortBy] = useState<'appliedDate' | 'company' | 'title' | 'salary'>('appliedDate');
  const [sortOrder, setSortOrder] = useState<'asc' | 'desc'>('desc');

  // View state
  const [viewMode, setViewMode] = useState<ViewMode>('board');

  // Modal state
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [selectedJob, setSelectedJob] = useState<Job | undefined>(undefined);

  // Hidden file input ref for JSON import
  const fileInputRef = useRef<HTMLInputElement>(null);

  // Handle opening modal for new job
  const handleNewJob = () => {
    setSelectedJob(undefined);
    setIsModalOpen(true);
  };

  // Handle opening modal for editing job
  const handleEditJob = (job: Job) => {
    setSelectedJob(job);
    setIsModalOpen(true);
  };

  // Handle modal submit
  const handleSaveJob = (jobData: Omit<Job, 'id' | 'updatedAt'> & { id?: string }) => {
    if (jobData.id) {
      updateJob(jobData as Job);
    } else {
      addJob(jobData);
    }
  };

  // Handle Sort Change
  const handleSort = (field: 'appliedDate' | 'company' | 'title' | 'salary') => {
    if (sortBy === field) {
      setSortOrder(sortOrder === 'asc' ? 'desc' : 'asc');
    } else {
      setSortBy(field);
      setSortOrder('desc'); // Default to descending
    }
  };

  // Export database
  const handleExport = () => {
    if (jobs.length === 0) {
      alert('No data to export.');
      return;
    }
    const dataStr = 'data:text/json;charset=utf-8,' + encodeURIComponent(JSON.stringify(jobs, null, 2));
    const downloadAnchor = document.createElement('a');
    downloadAnchor.setAttribute('href', dataStr);
    downloadAnchor.setAttribute('download', `careerpath_backup_${new Date().toISOString().split('T')[0]}.json`);
    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    downloadAnchor.remove();
  };

  // Import database trigger
  const handleImportClick = () => {
    fileInputRef.current?.click();
  };

  const handleImportFile = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    const fileReader = new FileReader();
    fileReader.onload = (event) => {
      try {
        const parsedData = JSON.parse(event.target?.result as string);
        const success = importData(parsedData);
        if (success) {
          alert('Data backup successfully imported!');
        } else {
          alert('Invalid backup format. Ensure it was generated by CareerPath.');
        }
      } catch {
        alert('Failed to parse file. Make sure it is a valid JSON.');
      }
    };
    fileReader.readAsText(file);
    e.target.value = ''; // Reset input
  };

  const handleReset = () => {
    if (confirm('Are you sure you want to restore the default sample data? This will overwrite your local changes.')) {
      resetData();
    }
  };

  // Filtered & Sorted Jobs
  const filteredJobs = useMemo(() => {
    return jobs
      .filter((job) => {
        const matchesSearch =
          job.title.toLowerCase().includes(search.toLowerCase()) ||
          job.company.toLowerCase().includes(search.toLowerCase()) ||
          (job.location && job.location.toLowerCase().includes(search.toLowerCase()));

        const matchesStatus = statusFilter === 'all' || job.status === statusFilter;
        const matchesLocationType = locationTypeFilter === 'all' || job.locationType === locationTypeFilter;

        return matchesSearch && matchesStatus && matchesLocationType;
      })
      .sort((a, b) => {
        let valA: string = '';
        let valB: string = '';

        if (sortBy === 'appliedDate') {
          valA = a.appliedDate || '';
          valB = b.appliedDate || '';
        } else if (sortBy === 'company') {
          valA = a.company.toLowerCase();
          valB = b.company.toLowerCase();
        } else if (sortBy === 'title') {
          valA = a.title.toLowerCase();
          valB = b.title.toLowerCase();
        } else if (sortBy === 'salary') {
          // crude extraction of first digits in salary string for numeric sort, else fallback
          const numA = parseInt((a.salary || '').replace(/[^0-9]/g, ''), 10) || 0;
          const numB = parseInt((b.salary || '').replace(/[^0-9]/g, ''), 10) || 0;
          return sortOrder === 'asc' ? numA - numB : numB - numA;
        }

        if (valA < valB) return sortOrder === 'asc' ? -1 : 1;
        if (valA > valB) return sortOrder === 'asc' ? 1 : -1;
        return 0;
      });
  }, [jobs, search, statusFilter, locationTypeFilter, sortBy, sortOrder]);

  if (!isLoaded) {
    return (
      <div className="flex flex-col items-center justify-center flex-1 h-screen bg-slate-50">
        <div className="flex flex-col items-center gap-3">
          <Briefcase className="h-10 w-10 text-indigo-600 animate-bounce" />
          <span className="text-sm font-bold text-slate-500 tracking-wider">
            Loading dashboard...
          </span>
        </div>
      </div>
    );
  }

  return (
    <div className="flex flex-col flex-1 bg-[#fafafa]">
      {/* Top Banner Navigation */}
      <header className="border-b border-slate-100 bg-white sticky top-0 z-40 shadow-xs">
        <div className="mx-auto max-w-7xl px-4 py-4 sm:px-6 lg:px-8 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
          <div className="flex items-center gap-2">
            <div className="h-9 w-9 bg-indigo-600 rounded-xl flex items-center justify-center text-white shadow-md shadow-indigo-100 shrink-0">
              <Briefcase className="h-5 w-5" />
            </div>
            <div>
              <h1 className="text-lg font-extrabold text-slate-800 tracking-tight leading-none">
                CareerPath
              </h1>
              <p className="text-[10px] text-slate-400 font-semibold uppercase mt-0.5 tracking-wider">
                Personal Job Application Tracker
              </p>
            </div>
          </div>

          {/* Database actions */}
          <div className="flex items-center gap-2">
            <button
              onClick={handleExport}
              title="Export JSON Backup"
              className="flex items-center gap-1.5 rounded-lg border border-slate-200 bg-white px-2.5 py-1.5 sm:px-3 text-xs font-semibold text-slate-600 hover:bg-slate-50 hover:text-slate-800 transition-all hover:shadow-xs cursor-pointer"
            >
              <Download className="h-3.5 w-3.5" /> <span className="hidden sm:inline">Export</span>
            </button>
            <button
              onClick={handleImportClick}
              title="Import JSON Backup"
              className="flex items-center gap-1.5 rounded-lg border border-slate-200 bg-white px-2.5 py-1.5 sm:px-3 text-xs font-semibold text-slate-600 hover:bg-slate-50 hover:text-slate-800 transition-all hover:shadow-xs cursor-pointer"
            >
              <Upload className="h-3.5 w-3.5" /> <span className="hidden sm:inline">Import</span>
            </button>
            <input
              type="file"
              ref={fileInputRef}
              onChange={handleImportFile}
              accept=".json"
              className="hidden"
            />
            <button
              onClick={handleReset}
              title="Reset to Sample Data"
              className="flex items-center gap-1.5 rounded-lg border border-slate-200 bg-white px-2.5 py-1.5 sm:px-3 text-xs font-semibold text-slate-500 hover:bg-red-50 hover:text-red-600 hover:border-red-100 transition-all hover:shadow-xs cursor-pointer"
            >
              <RotateCcw className="h-3.5 w-3.5" /> <span className="hidden sm:inline">Reset</span>
            </button>
          </div>
        </div>
      </header>

      {/* Main Content Area */}
      <main className="flex-1 mx-auto w-full max-w-7xl px-4 py-8 sm:px-6 lg:px-8 space-y-8 pb-20 sm:pb-8">
        {/* Statistics Panels */}
        <StatsHeader stats={stats} />

        {/* Filters and Navigation Toolbar */}
        <div className="flex flex-col gap-4 p-4 border border-slate-100 bg-white rounded-2xl shadow-xs lg:flex-row lg:items-center lg:justify-between">
          
          {/* View Modes Selector */}
          <div className="hidden sm:flex items-center p-1 rounded-xl bg-slate-50 border border-slate-100/50 self-start shrink-0">
            <button
              onClick={() => setViewMode('board')}
              className={`flex items-center gap-1.5 px-4 py-1.5 text-xs font-bold rounded-lg transition-all ${
                viewMode === 'board'
                  ? 'bg-white text-indigo-600 shadow-sm'
                  : 'text-slate-500 hover:text-slate-800'
              }`}
            >
              <LayoutGrid className="h-3.5 w-3.5" /> Kanban Board
            </button>
            <button
              onClick={() => setViewMode('list')}
              className={`flex items-center gap-1.5 px-4 py-1.5 text-xs font-bold rounded-lg transition-all ${
                viewMode === 'list'
                  ? 'bg-white text-indigo-600 shadow-sm'
                  : 'text-slate-500 hover:text-slate-800'
              }`}
            >
              <List className="h-3.5 w-3.5" /> List View
            </button>
            <button
              onClick={() => setViewMode('analytics')}
              className={`flex items-center gap-1.5 px-4 py-1.5 text-xs font-bold rounded-lg transition-all ${
                viewMode === 'analytics'
                  ? 'bg-white text-indigo-600 shadow-sm'
                  : 'text-slate-500 hover:text-slate-800'
              }`}
            >
              <BarChart3 className="h-3.5 w-3.5" /> Analytics
            </button>
          </div>

          {/* Quick Filters (Search, Status, Location) */}
          <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:flex-1 lg:justify-end">
            
            {/* Search Input */}
            <div className="relative flex-1 max-w-sm">
              <input
                type="text"
                placeholder="Search role, company, or location..."
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                className="w-full rounded-lg border border-slate-200 pl-9 pr-4 py-2 text-slate-800 text-xs placeholder:text-slate-400 focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 outline-hidden bg-white"
              />
              <Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400" />
            </div>

            {/* Status Select Filter */}
            <div>
              <select
                value={statusFilter}
                onChange={(e) => setStatusFilter(e.target.value as JobStatus | 'all')}
                className="w-full rounded-lg border border-slate-200 px-3 py-2 text-slate-800 text-xs focus:border-indigo-500 outline-hidden bg-white"
              >
                <option value="all">All Stages</option>
                <option value="saved">Saved</option>
                <option value="applied">Applied</option>
                <option value="interviewing">Interviewing</option>
                <option value="offer">Offer</option>
                <option value="rejected">Rejected</option>
              </select>
            </div>

            {/* Workplace Select Filter */}
            <div>
              <select
                value={locationTypeFilter}
                onChange={(e) => setLocationTypeFilter(e.target.value as LocationType | 'all')}
                className="w-full rounded-lg border border-slate-200 px-3 py-2 text-slate-800 text-xs focus:border-indigo-500 outline-hidden bg-white"
              >
                <option value="all">All Workplace Types</option>
                <option value="remote">Remote Only</option>
                <option value="hybrid">Hybrid Only</option>
                <option value="onsite">On-site Only</option>
              </select>
            </div>

            {/* Add Application Button */}
            <button
              onClick={handleNewJob}
              className="hidden sm:flex items-center justify-center gap-1.5 rounded-lg bg-indigo-600 hover:bg-indigo-700 px-4 py-2 text-xs font-bold text-white transition-colors shadow-sm shrink-0 cursor-pointer"
            >
              <Plus className="h-4 w-4" /> Track Position
            </button>
          </div>

        </div>

        {/* Swappable Layouts */}
        <div className="min-h-[50vh]">
          {viewMode === 'board' && (
            <KanbanBoard
              jobs={filteredJobs}
              onMoveJob={moveJob}
              onEditJob={handleEditJob}
            />
          )}

          {viewMode === 'list' && (
            <ListView
              jobs={filteredJobs}
              onEditJob={handleEditJob}
              sortBy={sortBy}
              sortOrder={sortOrder}
              onSort={handleSort}
            />
          )}

          {viewMode === 'analytics' && (
            <AnalyticsView jobs={jobs} />
          )}
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-slate-100 bg-white py-6 mt-12 text-center text-xs text-slate-400 font-medium">
        <p>© 2026 CareerPath Job Tracker. Fully persisted client-side in LocalStorage.</p>
      </footer>

      {/* Main Job Application Detail Form Modal */}
      <JobModal
        key={selectedJob ? selectedJob.id : (isModalOpen ? 'new' : 'closed')}
        isOpen={isModalOpen}
        onClose={() => setIsModalOpen(false)}
        job={selectedJob}
        onSave={handleSaveJob}
        onDelete={deleteJob}
      />

      {/* Mobile FAB — floats above the nav */}
      <button
        onClick={handleNewJob}
        className="sm:hidden fixed bottom-[72px] right-4 z-50 flex h-12 w-12 items-center justify-center rounded-full bg-indigo-600 text-white shadow-lg shadow-indigo-200/60 active:scale-95 active:shadow-md transition-all cursor-pointer"
        title="Track Position"
        type="button"
      >
        <Plus className="h-5 w-5 stroke-[2.5]" />
      </button>

      {/* Mobile Bottom Navigation Bar */}
      <nav className="sm:hidden fixed bottom-0 left-0 right-0 z-40 bg-white border-t border-slate-200/80 shadow-[0_-2px_8px_rgba(0,0,0,0.04)]">
        <div className="grid grid-cols-3 h-14">
          <button
            onClick={() => setViewMode('board')}
            className={`flex flex-col items-center justify-center gap-0.5 transition-colors cursor-pointer ${
              viewMode === 'board' ? 'text-indigo-600' : 'text-slate-400 active:text-slate-600'
            }`}
            type="button"
          >
            <LayoutGrid className="h-[22px] w-[22px]" />
            <span className={`text-[10px] leading-none ${viewMode === 'board' ? 'font-bold' : 'font-medium'}`}>Board</span>
          </button>

          <button
            onClick={() => setViewMode('list')}
            className={`flex flex-col items-center justify-center gap-0.5 transition-colors cursor-pointer ${
              viewMode === 'list' ? 'text-indigo-600' : 'text-slate-400 active:text-slate-600'
            }`}
            type="button"
          >
            <List className="h-[22px] w-[22px]" />
            <span className={`text-[10px] leading-none ${viewMode === 'list' ? 'font-bold' : 'font-medium'}`}>List</span>
          </button>

          <button
            onClick={() => setViewMode('analytics')}
            className={`flex flex-col items-center justify-center gap-0.5 transition-colors cursor-pointer ${
              viewMode === 'analytics' ? 'text-indigo-600' : 'text-slate-400 active:text-slate-600'
            }`}
            type="button"
          >
            <BarChart3 className="h-[22px] w-[22px]" />
            <span className={`text-[10px] leading-none ${viewMode === 'analytics' ? 'font-bold' : 'font-medium'}`}>Analytics</span>
          </button>
        </div>
      </nav>
    </div>
  );
}
