import { Job } from './types';

export const INITIAL_MOCK_JOBS: Job[] = [
  {
    id: 'mock-1',
    title: 'Senior Frontend Engineer',
    company: 'Stripe',
    status: 'offer',
    appliedDate: '2026-05-10',
    location: 'San Francisco, CA',
    locationType: 'hybrid',
    salary: '$160,000 - $190,000',
    url: 'https://stripe.com/jobs/senior-frontend-engineer',
    contact: {
      name: 'Sarah Jenkins',
      role: 'Technical Recruiter',
      email: 'sjenkins@stripe.com',
      phone: '555-0192',
    },
    resumeVersion: 'Resume_Frontend_Lead_2026.pdf',
    notes: 'The tech stack here is React, TypeScript, and Tailwind. Spoke with Sarah about their dashboard team. They are looking for someone to lead the UI redesign of the billing portal. \n\nNegotiated salary: base 175k + 25k bonus + equity.',
    tasks: [
      { id: 'mock-t1-1', title: 'Prepare for system design interview', completed: true, dueDate: '2026-05-18' },
      { id: 'mock-t1-2', title: 'Send thank-you email to hiring manager', completed: true, dueDate: '2026-05-20' },
      { id: 'mock-t1-3', title: 'Review offer details and equity compensation package', completed: false, dueDate: '2026-06-25' },
    ],
    updatedAt: '2026-06-15T14:30:00.000Z',
    submissionMethod: 'website',
    portalEmail: 'jobseeker.jane@gmail.com',
    portalUrl: 'https://stripe.workdayjobs.com/stripe',
    jobDescription: 'Stripe is looking for a Senior Frontend Engineer to build beautiful, highly interactive dashboard interfaces. Experience with React, TypeScript, state synchronization, and complex UI performance tuning is highly desired.',
    starStories: [
      {
        id: 'star-1-1',
        title: 'Billing Dashboard Redesign',
        situation: 'The legacy billing dashboard portal was loading slowly (over 4 seconds), leading to customer complaints.',
        task: 'I was tasked with leading a frontend optimization and UI refresh of the dashboard to decrease loading latency.',
        action: 'I migrated heavy data grids to use react-window virtualization, lazy-loaded offscreen charts, and refactored global context states to minimize unnecessary rerenders.',
        result: 'Dashboard initial load time dropped from 4.2s to 1.3s (69% reduction), and customer NPS increased by 15 points.',
      }
    ]
  },
  {
    id: 'mock-2',
    title: 'Software Engineer II (Next.js)',
    company: 'Vercel',
    status: 'interviewing',
    appliedDate: '2026-05-28',
    location: 'Remote',
    locationType: 'remote',
    salary: '$140,000 - $165,000',
    url: 'https://vercel.com/careers/software-engineer-nextjs',
    contact: {
      name: 'Michael Chen',
      role: 'Hiring Manager',
      email: 'mchen@vercel.com',
    },
    resumeVersion: 'Resume_React_Nextjs_Specialist.pdf',
    notes: 'Had a great conversation with Michael during the initial screen. Interview process has 3 stages:\n1. Technical screen (live coding)\n2. System architecture (Next.js internals, ISR/SSR, hydration)\n3. Culture fit. \n\nFocus on demonstrating knowledge of App Router optimization, Server Actions, and rendering architectures.',
    tasks: [
      { id: 'mock-t2-1', title: 'Complete Next.js coding challenge', completed: true, dueDate: '2026-06-05' },
      { id: 'mock-t2-2', title: 'System design interview: Next.js rendering pipeline', completed: false, dueDate: '2026-06-22' },
      { id: 'mock-t2-3', title: 'Prepare questions about Vercel AI SDK team', completed: false, dueDate: '2026-06-21' },
    ],
    updatedAt: '2026-06-18T09:15:00.000Z',
    submissionMethod: 'referral',
    portalEmail: 'jobseeker.jane@gmail.com',
    portalUrl: 'https://greenhouse.io/vercel/portal',
    jobDescription: 'Help us push the boundaries of Next.js and frontend development. You will build and optimize server-side components, collaborate with the React core team, and improve developer experience around Next.js App Router.',
    starStories: [
      {
        id: 'star-2-1',
        title: 'App Router Migration',
        situation: 'My previous employer had a complex Pages Router project that was hitting build size bottlenecks and hydration lags.',
        task: 'I planned and executed the modular migration of the client portal to Next.js App Router and React Server Components.',
        action: 'I separated static content blocks to Server Components, optimized image loading parameters, and leveraged Server Actions to deprecate 30+ redux boilerplate files.',
        result: 'Bundle sizes dropped by 45% and the mobile Lighthouse performance score jumped from 62 to 94.',
      }
    ]
  },
  {
    id: 'mock-3',
    title: 'UI/UX Developer',
    company: 'Figma',
    status: 'interviewing',
    appliedDate: '2026-06-02',
    location: 'New York, NY',
    locationType: 'hybrid',
    salary: '$130,000 - $155,000',
    url: 'https://figma.com/careers/ui-ux-developer',
    contact: {
      name: 'Elena Rostova',
      role: 'Lead UI Engineer',
      email: 'erostova@figma.com',
    },
    resumeVersion: 'Resume_Frontend_Design_2026.pdf',
    notes: 'Role is 50% design implementation and 50% frontend engineering. Figma is building out their next-gen whiteboarding tools. They love candidates who have a strong portfolio showcasing animations, canvas work, and layout precision.',
    tasks: [
      { id: 'mock-t3-1', title: 'Portfolio walkthrough prep', completed: true, dueDate: '2026-06-12' },
      { id: 'mock-t3-2', title: 'Schedule round 2 technical panel', completed: true, dueDate: '2026-06-15' },
      { id: 'mock-t3-3', title: 'Code demo: Custom canvas widget', completed: false, dueDate: '2026-06-24' },
    ],
    updatedAt: '2026-06-19T11:00:00.000Z',
    submissionMethod: 'linkedin',
    jobDescription: 'Build the future of Figma design systems and whiteboarding plugins. We seek developers who possess a strong eye for visual detail, can write raw canvas interactions, and excel at animation frameworks.',
  },
  {
    id: 'mock-4',
    title: 'Frontend Engineer',
    company: 'Airbnb',
    status: 'applied',
    appliedDate: '2026-06-08',
    location: 'Remote, US',
    locationType: 'remote',
    salary: '$150,000 - $180,000',
    url: 'https://airbnb.com/careers/frontend-engineer',
    contact: {
      name: 'David Ortiz',
      role: 'Sourcer',
    },
    resumeVersion: 'Resume_Frontend_Lead_2026.pdf',
    notes: 'Applied via employee referral from Jess. Airbnb is known for their high bar in frontend architecture, especially performance and accessibility. Need to brush up on Web Core Vitals and accessibility guidelines.',
    tasks: [
      { id: 'mock-t4-1', title: 'Follow up with Jess on referral status', completed: true, dueDate: '2026-06-15' },
      { id: 'mock-t4-2', title: 'Follow up with recruiter David Ortiz', completed: false, dueDate: '2026-06-23' },
    ],
    updatedAt: '2026-06-08T10:00:00.000Z',
    submissionMethod: 'referral',
  },
  {
    id: 'mock-5',
    title: 'Full Stack Developer',
    company: 'Supabase',
    status: 'applied',
    appliedDate: '2026-06-12',
    location: 'Remote',
    locationType: 'remote',
    salary: '$120,000 - $150,000',
    url: 'https://supabase.com/careers/full-stack-developer',
    resumeVersion: 'Resume_Fullstack_General_2026.pdf',
    notes: 'PostgREST, React, TypeScript, and Go. Interested in the Database/Dashboard features. Open source focus, so my GitHub contributions will be heavily scrutinized. Added links to my Postgres extensions projects in the cover letter.',
    tasks: [
      { id: 'mock-t5-1', title: 'Submit application through lever link', completed: true, dueDate: '2026-06-12' },
      { id: 'mock-t5-2', title: 'Refresh Postgres scripting and triggers knowledge', completed: false, dueDate: '2026-06-22' },
    ],
    updatedAt: '2026-06-12T16:45:00.000Z',
    submissionMethod: 'website',
  },
  {
    id: 'mock-6',
    title: 'Frontend Developer',
    company: 'Linear',
    status: 'saved',
    appliedDate: '2026-06-18',
    location: 'Remote',
    locationType: 'remote',
    salary: '$130,000 - $160,000',
    url: 'https://linear.app/careers/frontend-developer',
    notes: 'Linear is famous for its performance, keyboard shortcuts, and gorgeous minimalist design. The application requires answering short questions instead of sending a standard resume. Let\'s draft answers that show attention to details and user experience principles.',
    tasks: [
      { id: 'mock-t6-1', title: 'Draft application question answers', completed: false, dueDate: '2026-06-22' },
      { id: 'mock-t6-2', title: 'Record a video walkthrough of my side projects', completed: false, dueDate: '2026-06-23' },
    ],
    updatedAt: '2026-06-18T12:00:00.000Z',
    submissionMethod: 'other',
  },
  {
    id: 'mock-7',
    title: 'Web Engineer',
    company: 'GitHub',
    status: 'rejected',
    appliedDate: '2026-04-15',
    location: 'Remote',
    locationType: 'remote',
    salary: '$140,000 - $170,000',
    url: 'https://github.com/careers/web-engineer',
    contact: {
      name: 'Anna Kowalski',
      role: 'Talent Acquisition',
      email: 'akowalski@github.com',
    },
    resumeVersion: 'Resume_Fullstack_General_2026.pdf',
    notes: 'Received rejection email 3 weeks after applying. No feedback provided. Standard automated response. Will try to reapply in 6 months for a different team or role.',
    tasks: [
      { id: 'mock-t7-1', title: 'Send polite follow-up requesting feedback', completed: true, dueDate: '2026-05-10' },
    ],
    updatedAt: '2026-05-08T09:00:00.000Z',
    submissionMethod: 'website',
  },
];
